name: haskbot
version: 0.1.0.0

dependencies:
- base
- haskeline

library:
  source-dirs: src

executables:
  haskbot-console:
    main: MainConsole.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskbot

tests:
  haskbot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskbot
